"""Parse @mentions out of Telegram message text.

The orchestrator uses this to decide whether a group message is targeted
at a specific agent. Unknown @handles are ignored (no error) — this keeps
the routing logic simple: unknown mentions mean "not a routing hint."

Two forms of @mention are recognized:

  1. Full Telegram username match via ``username_to_agent`` — e.g. a real
     bot is ``@MAAS_manager_bot`` and the mapping says
     ``{"maas_manager_bot": "manager"}``. This is how real users actually
     @-mention the bots in Telegram clients.

  2. Short-form fallback against ``known_agents`` — e.g. ``@intelligence``.
     This is mainly used by internal handoff messages generated by the
     orchestrator itself (see Manager stub's handoff text). The ``_bot``
     suffix is stripped before matching.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping

_MENTION_RE = re.compile(r"@([A-Za-z][A-Za-z0-9_]*)")


def parse_mentions(
    text: str,
    known_agents: Iterable[str],
    username_to_agent: Mapping[str, str] | None = None,
) -> list[str]:
    known = {a.lower() for a in known_agents}
    u2a = {u.lower(): a.lower() for u, a in (username_to_agent or {}).items()}
    out: list[str] = []
    for match in _MENTION_RE.finditer(text):
        handle = match.group(1).lower()
        # Try full Telegram username match first.
        if handle in u2a:
            out.append(u2a[handle])
            continue
        # Fallback: strip _bot suffix and check against known short names.
        short = handle[: -len("_bot")] if handle.endswith("_bot") else handle
        if short in known:
            out.append(short)
    return out
